collections:
  authors:
    output: true

kramdown:
  input: GFMKatex

  
url:  # the base hostname and protocol for your site, e.g. http://example.com
baseurl:       # place folder name if the site is served in a subfolder
icon: /assets/img/favicon.png


defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"


mathjax:
  version: "3.2.2"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
